services:

##########################################
##
## relational data
##
##########################################

    mariadb-database-server:

        container_name: mariadb-database-server

        image: mariadb:latest

        restart: unless-stopped

        ports:

            - "3306:3306"
                    
        environment:

            MYSQL_ROOT_PASSWORD: aggiepride

            MYSQL_DATABASE: shinobi

            MYSQL_USER: shinobi

            MYSQL_PASSWORD: shinobi

        volumes:

            - /volumes/database:/var/lib/mysql
            
    mariadb-database-admin:

        container_name: mariadb-database-admin

        image: beeyev/phpmyadmin-lightweight

        depends_on:

           - mariadb-database-server

        links:

           - mariadb-database-server

        ports:

            - "3380:80"

        environment:

            PMA_HOST: mariadb-database-server
